### PR TITLE
WIP: ENH: optimize.linprog: use highspy for _linprog_highs

### PR DESCRIPTION
**Pull request by mckib2**
#### What does this implement/fix?

- removes Cython wrapper in favor of upstream highspy extensions as discussed in gh-15915
    - includes `_highs_options` and `_highs_constants` C extensions to access APIs and constants not available from pybind11 interfaces directly
- updates to latest upstream HiGHS master including meson build system port

#### Additional information

TODO:
- [x] fix `milp` (it's completely broken currently)
- [x] port build system updates to legacy `setup.py`
- [x] HiGHS option passing, sanitation
- [x] grab enum values not exposed by pybind extension
- [x] fix linting issues
- [x] -error handling in `_highs_constants`- no meaningful way to handle this error
- [x] test on mac
- [ ] test on windows -- I still can't figure out how to build on windows...

### CODE REVIEW

**Comment by mckib2** [comment]
@mdhaber There are two remaining `linprog` failures (same test for HiGHS SimplexDual and IPM) after updating to the latest version of HiGHS and using the upstream pybind11 interface.  We're expecting a status of infeasible for [`test_bounds_infeasible_2`](https://github.com/scipy/scipy/blob/5a1ad4c42b033eb65cbc8694f837480c81c5247c/scipy/optimize/tests/test_linprog.py#L611) but get a status of `NOT SET` instead.  The issue is the same for both `bounds_1` and `bounds_2`.  This looks like a upstream regression to me -- it seems like they should be setting some solve status besides `NOT SET`.

<details>

```
================================================================================================ FAILURES =================================================================================================
__________________________________________________________________________ TestLinprogHiGHSSimplexDual.test_bounds_infeasible_2 ___________________________________________________________________________
scipy/optimize/tests/test_linprog.py:645: in test_bounds_infeasible_2
    _assert_infeasible(res)
        bounds_1   = [(1, 2), (inf, inf), (3, 4)]
        bounds_2   = [(1, 2), (-inf, -inf), (3, 4)]
        c          = [1, 2, 3]
        do_presolve = True
        res        =        message: (HiGHS Status 0: Not Set)
       success: False
        status: 4
           fun: None
             x:... eqlin:  residual: None
                marginals: None
       ineqlin:  residual: None
                marginals: None
        self       = <scipy.optimize.tests.test_linprog.TestLinprogHiGHSSimplexDual object at 0x7f961837f670>
        simplex_without_presolve = False
scipy/optimize/tests/test_linprog.py:41: in _assert_infeasible
    assert_equal(res.status, 2, "failed to report infeasible status")
E   AssertionError: 
E   Items are not equal: failed to report infeasible status
E    ACTUAL: 4
E    DESIRED: 2
        res        =        message: (HiGHS Status 0: Not Set)
       success: False
        status: 4
           fun: None
             x:... eqlin:  residual: None
                marginals: None
       ineqlin:  residual: None
                marginals: None
______________________________________________________________________________ TestLinprogHiGHSIPM.test_bounds_infeasible_2 _______________________________________________________________________________
scipy/optimize/tests/test_linprog.py:645: in test_bounds_infeasible_2
    _assert_infeasible(res)
        bounds_1   = [(1, 2), (inf, inf), (3, 4)]
        bounds_2   = [(1, 2), (-inf, -inf), (3, 4)]
        c          = [1, 2, 3]
        do_presolve = True
        res        =        message: (HiGHS Status 0: Not Set)
       success: False
        status: 4
           fun: None
             x:... eqlin:  residual: None
                marginals: None
       ineqlin:  residual: None
                marginals: None
        self       = <scipy.optimize.tests.test_linprog.TestLinprogHiGHSIPM object at 0x7f9618370580>
        simplex_without_presolve = False
scipy/optimize/tests/test_linprog.py:41: in _assert_infeasible
    assert_equal(res.status, 2, "failed to report infeasible status")
E   AssertionError: 
E   Items are not equal: failed to report infeasible status
E    ACTUAL: 4
E    DESIRED: 2
        res        =        message: (HiGHS Status 0: Not Set)
       success: False
        status: 4
           fun: None
             x:... eqlin:  residual: None
                marginals: None
       ineqlin:  residual: None
                marginals: None
========================================================================================= short test summary info =========================================================================================
FAILED scipy/optimize/tests/test_linprog.py::TestLinprogHiGHSSimplexDual::test_bounds_infeasible_2 - AssertionError: 
FAILED scipy/optimize/tests/test_linprog.py::TestLinprogHiGHSIPM::test_bounds_infeasible_2 - AssertionError: 
============================================================== 2 failed, 828 passed, 18 skipped, 1 deselected, 2 xfailed, 2 xpassed in 7.21s ==============================================================
```

</details>

If you agree this looks like a regression, I can raise the issue with the HiGHS team

**Comment by mdhaber** [comment]
Yes, reporting a status seems like a better thing to do.

**Comment by mckib2** [comment]
> Yes, reporting a status seems like a better thing to do.

Reviewed this a little -- looks like we had some logic in the old highs wrapper to capture this error case.  (If you're interested: if the model is nonsense and fails to load, the error code is not updated, so we manually set a model error in this case)

**Comment by mckib2** [comment]
@mdhaber I'm a little rusty with `setup.py` in-place builds...  How do you run the `test_linprog.py` tests after successfully building, e.g., `python setup.py build_ext --inplace`?

**Comment by mdhaber** [comment]
Now that `runtests.py` is gone I rely on Pycharm. It's able to run a whole file or individual tests.

**Pull request closed without merging**
