### PR TITLE
TST: sparse.linalg: propack: add test against example provided with PROPACK

### PR DESCRIPTION
**Pull request by mdhaber**
#### Reference issue
gh-9

#### What does this implement/fix?
Adds a unit test against example problem/data provided with PROPACK

#### Additional information

- Single-precision results don't match the output provided with propack super closely. It's mostly a good SVD (i.e. `u@np.diag(s)@vt` is close to the original matrix) but there are a few elements of that comparison that don't match as well as we might expect (e.g. worst relative error is 0.00312401)
- The data files are large. Can you include them in the zip folder?
- I can't easily read the format for the complex examples
- This should be all set to parametrize over `irl` `True/False`

### CODE REVIEW

**Comment by mckib2** [comment]
> The data files are large. Can you include them in the zip folder?

That's a good question -- it seems like adding test data as zip files is something that's okay, but given the experience with Boost, maybe we should unzip the PROPACK sources?

**Comment by mdhaber** [comment]
Probably. Since the source is not that big and unlikely to be updated, probably should do it like SuperLU.  So never mind; I guess I'll just compress the results.

**Comment by mdhaber** [comment]
`.gitignore` indicates that I should just commit the source and rely on git's built-in compression. Fine. I guess I should just revert.

**Comment by mckib2** [comment]
Good to merge?

**Comment by mdhaber** [comment]
I guess. I hate these files showing in the diff though. I could convert to `.npz` but I want it to be clear that they're straight from PROPACK.

**Pull request merged**
